### ISSUE TITLE
Disabled button makes user confused in previous steps

### ISSUE THREAD

**Issue by dw511214992** [test-repo-billy/azure-sdk-tools#10]
feedback from @chunyu3 
We have disabled all buttons in previous steps. Crystal is confused and didn't know why the button is confused because she may think there is some neceessary information no provided, which disables the button.

**Comment by honghr** [comment]
API Readiness App has been fixed. @zzvswxy will fix it in SDK Release App.

**Comment by zzvswxy** [comment]
will add tips when a button is disabled

**Comment by zzvswxy** [comment]
![Image](https://user-images.githubusercontent.com/20081898/204429180-a42e23fe-b9fe-4faf-a99d-9279fcffd536.png)
