### ISSUE TITLE
Api Readiness App Welcome page's start button should be disabled when all steps have been finished.

### ISSUE THREAD

**Issue by dw511214992** [test-repo-billy/azure-sdk-tools#11]
feedback from @chunyu3 

![image](https://user-images.githubusercontent.com/40835867/203234173-f3178ad7-037e-4174-9272-c1a4c045e3f1.png)

**Comment by live1206** [comment]
SDK release App should follow this.

**Comment by zzvswxy** [comment]
when the step is completed, the next button will always be editable.
