### ISSUE TITLE
[typo] API reference should be published in azure-rest-api-specs, not azure-rest-api-specs-pr repo

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-sdk-tools#13]
![image](https://user-images.githubusercontent.com/18413981/203254171-5c7f95b2-5092-4bc8-82d8-1eb3083958ac.png)

**Comment by akning-ms** [comment]
docs.miscrosoft.com also should be changed to learn.microsoft.com, right?

**Comment by live1206** [comment]
Fixed and deployed in PPE
<img width="723" alt="image" src="https://user-images.githubusercontent.com/5196139/204204458-ec38dec3-c88b-4836-92fa-efa44fc7d70f.png">
