### ISSUE TITLE
The first page task is confusing

### ISSUE THREAD

**Issue by ruowan** [test-repo-billy/azure-sdk-tools#14]
<img width="1480" alt="Screenshot 2022-11-22 at 15 41 58" src="https://user-images.githubusercontent.com/52271048/203254696-30be3f8f-0771-4cdd-8b70-0eb2061cbcf4.png">

I expected when I click one of these link, I go to another flow. But seems these link will navigate to toolset section. It's confusing.

And is there any sequence requirement for the navigation panel?

**Comment by live1206** [comment]
Only keep below
[Repo Permissions on GitHub - Overview (azure.com)](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/4/Repo-Permissions-on-GitHub)
[DevOps Permissions - Overview (azure.com)](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/68/DevOps-Permissions)
