### ISSUE TITLE
The "select user to add" does not function well

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-sdk-tools#15]
![image](https://user-images.githubusercontent.com/18413981/203254915-4a97fc9f-899c-49c8-9ac2-89662ccd6e05.png)
![image](https://user-images.githubusercontent.com/18413981/203255052-0f313fa1-87cf-4101-95ee-3fbf7527d5a8.png)
![image](https://user-images.githubusercontent.com/18413981/203255163-a60fb8be-20be-40ed-9906-2559a271fdf0.png)
![image](https://user-images.githubusercontent.com/18413981/203255374-4ad7e328-418e-4148-91d7-0fd9ab6c229c.png)

**Comment by honghr** [comment]
power apps doesn't support sorting search results by similarity, so I've changed this to ascending order and only support alias sorting
