### ISSUE TITLE
Unable to support multiple requests within one RP

### ISSUE THREAD

**Issue by qiaozha** [test-repo-billy/azure-sdk-tools#18]
![image](https://user-images.githubusercontent.com/55688292/203255540-529a4936-81a1-475f-bb6d-69320fbccfcb.png)
This is probably not very friendly to those big RP with multiple sub teams.

**Comment by live1206** [comment]
The work item is corresponding to 1 product, if 1 RP contains multiple products, they can onboard and create multiple work items.
