### ISSUE TITLE
Submit onboarding APEX failure

### ISSUE THREAD

**Issue by ruowan** [test-repo-billy/azure-sdk-tools#21]
<img width="1693" alt="Screenshot 2022-11-22 at 15 55 21" src="https://user-images.githubusercontent.com/52271048/203257073-dba6f905-58d4-4424-97f5-a6f38a5d28dc.png">

**Comment by ruowan** [comment]
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/52271048/203257497-7b518271-d426-4ffc-a39b-e26d5b017de8.png">

**Comment by leniatgh** [comment]
Same issue:
![image](https://user-images.githubusercontent.com/7233663/203258409-80acfa1f-6531-4170-96a8-e0e682bade90.png)

**Comment by live1206** [comment]
Child flow was turn off in PPE, fixed and verified in PPE
