### ISSUE TITLE
Error UpdateOnboardingQuestionnaire.Run failed when submitting the onboarding product step

### ISSUE THREAD

**Issue by MaryGao** [test-repo-billy/azure-sdk-tools#23]
UpdateOnboardingQuestionnaire.Run failed: The data returned in the response is invalid. Response data should be a valid JSON object.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/9943211/203257524-0ee317dd-b1aa-48a1-90aa-377a25705d33.png)

**Comment by live1206** [comment]
Latest deploy to PPE
