### ISSUE TITLE
[UX] Delete a member does not have confirmation

### ISSUE THREAD

**Issue by fengzhou-msft** [test-repo-billy/azure-sdk-tools#28]
<img width="1580" alt="image" src="https://user-images.githubusercontent.com/55177366/203255166-f3dee6e1-81d9-475f-9393-bdc8350a8abe.png">

When clicking the button to delete a member, there's no prompt to confirm the deletion. There could be 

And an owner can delete himself/herself, would that cause any issue.

**Comment by live1206** [comment]
Since this data is not important and can be added easily, no need to confirm.
