### ISSUE TITLE
meeting is scheduled after one click?

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-sdk-tools#29]
![image](https://user-images.githubusercontent.com/18413981/203258951-be47b0d1-1b97-4252-b5e8-71ce28996054.png)

The experience is unexpected - after clicking "schedule a meeting" it opens the scheduling app, and the meeting shows up in the table even I haven't click 'create' button in the scheduling app.

**Comment by josefree** [comment]
meeting should be scheduled only after user clicks 'create' button in the scheduling app.

**Comment by josefree** [comment]
seems SDK app has the same issue
![image](https://user-images.githubusercontent.com/18413981/203263742-7d7eca54-a02a-4d3c-986b-d6c67cb67193.png)

**Comment by dw511214992** [comment]
I think we shouldn't display draft meetings

**Comment by live1206** [comment]
Validate only 1 draft meeting with 1 type while creating meeting

**Comment by zzvswxy** [comment]
SDK Release App fixed it. Validate only 1 draft meeting with 1 type while creating meeting and don't show draft meeting in the Apps.

**Comment by live1206** [comment]
> Validate only 1 draft meeting with 1 type while creating meeting

We can leave the draft meeting as it is, no validation
