### ISSUE TITLE
What' is SDK Onboarding Questionnaire

### ISSUE THREAD

**Issue by leniatgh** [test-repo-billy/azure-sdk-tools#32]
> "Ensure to complete the SDK Onboarding Questionnaire first for the selected product."

The SDK Onboarding Questionnaire refers to "Onboard APEX Product"? If so, we could make the name consistent.

![image](https://user-images.githubusercontent.com/7233663/203259764-5ea952a5-3d95-4c72-8925-881239aede47.png)

**Comment by live1206** [comment]
Fixed and deployed to PPE
