### ISSUE TITLE
The link to doc site for queue length is not clear

### ISSUE THREAD

**Issue by akning-ms** [test-repo-billy/azure-sdk-tools#33]
![image](https://user-images.githubusercontent.com/57385816/203260283-76bcb6f3-e712-4987-a060-a9762c85553c.png)

**Comment by akning-ms** [comment]
The link for "queue length"  in doc site  is checking queue length? seems I can not find it. 
![image](https://user-images.githubusercontent.com/57385816/203261038-9d313416-3f7c-423f-9cbd-e6b3c6b6a6df.png)

if not,  we may not need this hyper link

**Comment by live1206** [comment]
Remove the link

**Comment by live1206** [comment]
Removed and deployed to PPE
