### ISSUE TITLE
The hint message does not disappear after focus moves onto

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-sdk-tools#34]
![image](https://user-images.githubusercontent.com/18413981/203261297-bfaf612e-7df1-4a76-8ec7-918e3dd04ccf.png)

**Comment by josefree** [comment]
![image](https://user-images.githubusercontent.com/18413981/203261802-fdeb6410-7b16-4fa9-97d7-23821c205015.png)

**Comment by zzvswxy** [comment]
will fix it in next version
![image](https://user-images.githubusercontent.com/20081898/203265357-99eb30dc-0429-4ea8-8f42-a95d8c689078.png)

![image](https://user-images.githubusercontent.com/20081898/203265465-c7e3337f-94ad-4f29-9263-249082fa318c.png)
