### ISSUE TITLE
The product name is incorrect in Release Planner page

### ISSUE THREAD

**Issue by MaryGao** [test-repo-billy/azure-sdk-tools#35]
In below image the produce name should not be `productsku health decistion support` but `Confidential ledger`.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/9943211/203261338-536a065d-0faf-474f-86af-61eebb50ffb7.png)

**Comment by live1206** [comment]
Fixed and deployed in PPE
<img width="858" alt="image" src="https://user-images.githubusercontent.com/5196139/204204555-0c4cfc72-45f4-430b-8dad-44065cea46b8.png">
