### ISSUE TITLE
Why the schedule app always refresh when click navigation panel 

### ISSUE THREAD

**Issue by ruowan** [test-repo-billy/azure-sdk-tools#37]
<img width="1528" alt="Screenshot 2022-11-22 at 16 20 37" src="https://user-images.githubusercontent.com/52271048/203262112-8ff6633a-9f43-4305-a853-2e5c432bd0ef.png">

**Comment by dw511214992** [comment]
I will report it to mariana

**Comment by dw511214992** [comment]
Because they are in different app, and powerapps will refresh the page automatically.
