### ISSUE TITLE
[experience enhance] date picker when select date to release SDKs

### ISSUE THREAD

**Issue by josefree** [test-repo-billy/azure-sdk-tools#38]
in the initial panel, can we grey all dates earlier than today 
when to revise the release date, can we grey all dates earlier than the specified date? which means we only allow to revise the sdk release date later than initial date.

**Comment by honghr** [comment]
Hi @josefree, Presently there is no way of preventing users selecting dates using the properties of the PowerApps date picker control. But I can display a error message and reset date picker to today when user selected date earlier than today.
