### ISSUE TITLE
Add notes in milestones page to indicate there exists dependency between Readness App and Release App

### ISSUE THREAD

**Issue by MaryGao** [test-repo-billy/azure-sdk-tools#42]
- It seems that we have to go to readness app first to do preparing and then go to release app. But there is hint for this message in milestones page.
- Also after I finish all steps in readness app there is no guidance for next step, go to release app or back to the main planer app?

![Untitled picture](https://user-images.githubusercontent.com/9943211/203264232-29c378ca-c6fa-433f-8502-661550e2bc81.png)

**Comment by live1206** [comment]
Add "You may click a link in the following table to go to release plan apps to complete release tasks." above table
