### ISSUE TITLE
Connector auth failed and casue browser crash on Mac M1 chip

### ISSUE THREAD

**Issue by ruowan** [test-repo-billy/azure-sdk-tools#45]
<img width="1334" alt="Screenshot 2022-11-22 at 16 36 48" src="https://user-images.githubusercontent.com/52271048/203266419-7580f910-0913-4995-a544-0e78e8d0ec76.png">

**Comment by live1206** [comment]
Created https://github.com/Azure/azure-sdk-tools/issues/4839 for tracking
