### ISSUE TITLE
After going through the checklist, what can user do?

### ISSUE THREAD

**Issue by leniatgh** [test-repo-billy/azure-sdk-tools#46]
"Prerequisite Checks", "Design and Define Service APIs" are not editable, but "Activate a Pull Request" is editable.

Is this by design?

**Comment by leniatgh** [comment]
After completing the "Data Plane API Readiness" milestone, the Pull Request can still be updated. Can user reuse the release plan for new Swagger PR?

**Comment by live1206** [comment]
Rest following steps in API readiness if reset PR

**Comment by live1206** [comment]
Disable "Activate a Pull Request" if "Data Plane API Readiness" is complete

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/204292754-61443253-22cf-4a16-8fe9-f67e4edb589d.png)

**Comment by honghr** [comment]
When user want to update pr, the popup warning will display. And then clicked button, the status will be reset.
