### ISSUE TITLE
Change the pr title name to spec pr or cadl pr when scheduling the meeting

### ISSUE THREAD

**Issue by MaryGao** [test-repo-billy/azure-sdk-tools#47]
Change the pr title name to spec pr or cadl pr when scheduling the meeting and should not be swagger pr here.

![Untitled picture](https://user-images.githubusercontent.com/9943211/203268742-340c3189-a020-4c40-9220-fbad0fbee8bf.png)

**Comment by dw511214992** [comment]
I will talk it to Mariana's team

**Comment by live1206** [comment]
https://github.com/Azure/azure-sdk-tools/issues/4791 created for follow-up
