### ISSUE TITLE
"Refresh" button is disabled in Step 2.1

### ISSUE THREAD

**Issue by leniatgh** [test-repo-billy/azure-sdk-tools#48]
![image](https://user-images.githubusercontent.com/7233663/203268971-b6b40f71-1b27-4adc-81da-631e7aa6521d.png)

The "Refresh" button is disabled. How can user know the latest status? Just wait for the page to auto refresh or need manually fresh the PowerApp page?

**Comment by leniatgh** [comment]
After completion, the "Refresh" button is enabled. Clicking it triggers a new build:
![image](https://user-images.githubusercontent.com/7233663/203271300-28db7c26-7742-4e8e-b009-cb340ca3010c.png)

I thought it's just to refresh status, and didn't expect to trigger a new build

**Comment by dw511214992** [comment]
Yes, the refresh button is for regenerating sdks. We may need to improve the experience.

**Comment by leniatgh** [comment]
![image](https://user-images.githubusercontent.com/7233663/203275686-22a3eeca-410c-40e1-989b-c0036baa119d.png)

**Comment by zzvswxy** [comment]
Thanks for the suggestions. Refresh button will be renamed to regenerate.  
And all the page in SDK Release app will refresh automatically, but the UX may need more improvement.
