### ISSUE TITLE
Add a new check in Sign off API Spec Readiness page

### ISSUE THREAD

**Issue by dw511214992** [test-repo-billy/azure-sdk-tools#5]
Feedback from @chunyu3 

![image](https://user-images.githubusercontent.com/40835867/202999141-a4dc356d-8507-4a11-b887-187ca7f826c3.png)

If there is sdk generated failed, we need to add a label to indicate the failure can be ignroed. If the label doesn't exist, we should block customer from completing the task.

**Comment by live1206** [comment]
Created https://github.com/Azure/azure-sdk-tools/issues/4838 for tracking
