### ISSUE TITLE
Suggest to have a refresh button to get the latest status of other two apps

### ISSUE THREAD

**Issue by MaryGao** [test-repo-billy/azure-sdk-tools#50]
Suggest to have a refresh button to allow users to get the latest status of other two apps otherwise I will close this page and then reopen it.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/9943211/203271467-4debaf20-bc3f-4888-9adb-083a4409e8e7.png)

**Comment by dw511214992** [comment]
the page will refresh itself automatically. Have you found that the page is not refreshed?
