### ISSUE TITLE
Suggest to have progress bar or notes when preparing the SDK prs

### ISSUE THREAD

**Issue by MaryGao** [test-repo-billy/azure-sdk-tools#51]
The whole page would be stuck here when preparing the SDK prs and to have a better experience we would add a fake progress bar for pipeline progress. Or just a note with below message.

Another thing is the refreshing buttong grey out. Could we try to enable it?

```
It may take 10 ~ 15 mins and please wait carefullu ... (the last dots would be dynamicly showed)
```

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/9943211/203273282-3133b975-69d0-4870-af99-be110a494eab.png)

**Comment by live1206** [comment]
indent and line gap adjustment

**Comment by zzvswxy** [comment]
will add a loading icon before language

**Comment by zzvswxy** [comment]
![Image](https://user-images.githubusercontent.com/20081898/203711293-47460642-0996-4f6f-b514-29edace13a68.png)
