### ISSUE TITLE
Checkboxes on Step 2.2 not clickable

### ISSUE THREAD

**Issue by leniatgh** [test-repo-billy/azure-sdk-tools#52]
![image](https://user-images.githubusercontent.com/7233663/203273792-3e4d36ae-25ce-4fcf-8f85-c7f47d317d4d.png)

Step2.1 has been completed:
![image](https://user-images.githubusercontent.com/7233663/203274027-cf74446e-f606-4a62-bc0d-81be6588978c.png)

**Comment by dw511214992** [comment]
we should disable refresh button when go to 2.2 and back to 2.1.

**Comment by live1206** [comment]
Progress status display to improve.

**Comment by live1206** [comment]
refresh -> regenerate
