### ISSUE TITLE
customer cannot select desired spec folder for new service

### ISSUE THREAD

**Issue by dw511214992** [test-repo-billy/azure-sdk-tools#54]
![image](https://user-images.githubusercontent.com/40835867/203493958-d8a8f3bb-0d99-44bb-93c1-f470184e833d.png)
If the service is new and needs a new spec folder, customer cannot select desired spec folder.

**Comment by live1206** [comment]
For new service, warn to onboard shift-left.
Get the RP folder from service team from PM, input to dataverse manually beforehand.
Or add a new field for this in ADO work item during informational meeting.

**Comment by honghr** [comment]
Remove this popup, but we need fill rp folder manually beforehand.
