### ISSUE TITLE
Don't show all sdk info when some sdks are not selected

### ISSUE THREAD

**Issue by dw511214992** [test-repo-billy/azure-sdk-tools#6]
Feedback from @chunyu3 

![image](https://user-images.githubusercontent.com/40835867/202999551-463140f0-0610-4083-bece-105c358b7c13.png)
If I don't select JS SDK, please don't show JS repo info

**Comment by zzvswxy** [comment]
![Image](https://user-images.githubusercontent.com/20081898/203488407-8be99a6c-deeb-4351-a9e5-6a1c2908a6d8.png)
